<a href="https://colab.research.google.com/github/varnika1008/varnika/blob/main/WoC_6_0_Checkpoint_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ARRAY

In [ ]:
import numpy as np

x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


ZEROS

In [ ]:
y=np.zeros(4)
print(y)
z=np.zeros((2,3))
print(z)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


ONES

In [ ]:
a=np.ones(4)
print(a)
b=np.ones([3,3])
print(b)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


RESHAPE

In [ ]:
arry=np.array([1,2,3,4])
reshape=arry.reshape(2,2)
print(reshape)

[[1 2]
 [3 4]]


CONCATENATE

In [ ]:
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])
concat=np.concatenate((c,d))
print(concat)

[1 2 3 4 5 6 7 8]


MEAN

In [ ]:
arry=np.array([1,2,3,4])
mean=np.mean(arry)
print(mean)

2.5


SUM

In [ ]:
sum=np.sum(arry)
print(sum)

10


MINIMUM

In [ ]:
min=np.min(arry)
print(min)

1


MAXIMUM

In [ ]:
max=np.max(arry)
print(max)

4


ARGMAX

In [ ]:
armax=np.argmax(arry)
print(armax)

3


ARGMIN

In [ ]:
armin=np.argmin(arry)
print(armin)

0


RANDOM

In [ ]:
rand=np.random.rand(2,3)
print(rand)

[[0.84649824 0.78375432 0.64273399]
 [0.38282968 0.25055051 0.02596192]]


random.randn

In [ ]:
randn=np.random.randn(2,4)
print(randn)

[[ 0.22422335  0.75464885 -0.4695166  -0.50818761]
 [-0.64533663 -0.72222112 -0.00809768  0.25388894]]


random.randint

In [ ]:
randint=np.random.randint(3,5)
print(randint)

4


DOT

In [ ]:
dot=np.dot(5,2)
print(dot)

10
